name: Dart Analyzer to SARIF
on: [push]
jobs:
  dart-analyzer:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    name: Dart Analyzer to SARIF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Scan files
        uses: yash-deepsource/community-analyzers-action@main
        with:
          ref: ${{ github.action_ref }}
          analyzer: "dart-analyze"
          deepsource-dsn: ${{ secrets.DEEPSOURCE_DSN }}
          version: "beta"
